name: "Website"
app_id: "yeti-www"
customer_id: "yeti"
version: "1.0.0"
description: "yetirocks.com marketing site + demos"
route_prefix: "/"

schemas:
  - schemas/schema.graphql

static_files:
  path: web
  spa: true
  build:
    sourceDir: source
    command: npm run build
