name: "Website"
app_id: "www"
customer_id: "yeti"
version: "1.0.0"
description: "yetirocks.com marketing site + demos"

schemas:
  path: schemas/schema.graphql

resources:
  path: "resources/*.rs"
  root: /api

static:
  path: web
  root: /
  spa: true
  build:
    source: source
    command: npm install && npm run build
