environment: production
port: 443

logging:
  level: info

tls:
  autoGenerate: true

applications:
  root_app: www
  autoLoad:
    - https://github.com/yetirocks/yeti-documentation
    - https://github.com/yetirocks/demo-basic
    - https://github.com/yetirocks/demo-fiql
    - https://github.com/yetirocks/demo-graphql
    - https://github.com/yetirocks/demo-realtime
    - https://github.com/yetirocks/demo-vector
    - https://github.com/yetirocks/demo-authentication
