/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as SolutionsUseCasesRouteImport } from './routes/solutions/use-cases'
import { Route as SolutionsFabricRouteImport } from './routes/solutions/fabric'
import { Route as SolutionsAiRouteImport } from './routes/solutions/ai'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal/terms-of-service'
import { Route as LegalSupportPolicyRouteImport } from './routes/legal/support-policy'
import { Route as LegalSoftwareLicenseRouteImport } from './routes/legal/software-license'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal/privacy-policy'
import { Route as LegalCookiePolicyRouteImport } from './routes/legal/cookie-policy'
import { Route as LegalAcceptableUseRouteImport } from './routes/legal/acceptable-use'
import { Route as DevelopersGettingStartedRouteImport } from './routes/developers/getting-started'
import { Route as DevelopersDemosRouteImport } from './routes/developers/demos'
import { Route as DevelopersBenchmarksRouteImport } from './routes/developers/benchmarks'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsUseCasesRoute = SolutionsUseCasesRouteImport.update({
  id: '/solutions/use-cases',
  path: '/solutions/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsFabricRoute = SolutionsFabricRouteImport.update({
  id: '/solutions/fabric',
  path: '/solutions/fabric',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAiRoute = SolutionsAiRouteImport.update({
  id: '/solutions/ai',
  path: '/solutions/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSupportPolicyRoute = LegalSupportPolicyRouteImport.update({
  id: '/legal/support-policy',
  path: '/legal/support-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSoftwareLicenseRoute = LegalSoftwareLicenseRouteImport.update({
  id: '/legal/software-license',
  path: '/legal/software-license',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiePolicyRoute = LegalCookiePolicyRouteImport.update({
  id: '/legal/cookie-policy',
  path: '/legal/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAcceptableUseRoute = LegalAcceptableUseRouteImport.update({
  id: '/legal/acceptable-use',
  path: '/legal/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersGettingStartedRoute =
  DevelopersGettingStartedRouteImport.update({
    id: '/developers/getting-started',
    path: '/developers/getting-started',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevelopersDemosRoute = DevelopersDemosRouteImport.update({
  id: '/developers/demos',
  path: '/developers/demos',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersBenchmarksRoute = DevelopersBenchmarksRouteImport.update({
  id: '/developers/benchmarks',
  path: '/developers/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/company': typeof CompanyRoute
  '/platform': typeof PlatformRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/developers/benchmarks': typeof DevelopersBenchmarksRoute
  '/developers/demos': typeof DevelopersDemosRoute
  '/developers/getting-started': typeof DevelopersGettingStartedRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/cookie-policy': typeof LegalCookiePolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/software-license': typeof LegalSoftwareLicenseRoute
  '/legal/support-policy': typeof LegalSupportPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/solutions/ai': typeof SolutionsAiRoute
  '/solutions/fabric': typeof SolutionsFabricRoute
  '/solutions/use-cases': typeof SolutionsUseCasesRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/company': typeof CompanyRoute
  '/platform': typeof PlatformRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/developers/benchmarks': typeof DevelopersBenchmarksRoute
  '/developers/demos': typeof DevelopersDemosRoute
  '/developers/getting-started': typeof DevelopersGettingStartedRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/cookie-policy': typeof LegalCookiePolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/software-license': typeof LegalSoftwareLicenseRoute
  '/legal/support-policy': typeof LegalSupportPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/solutions/ai': typeof SolutionsAiRoute
  '/solutions/fabric': typeof SolutionsFabricRoute
  '/solutions/use-cases': typeof SolutionsUseCasesRoute
  '/legal': typeof LegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/company': typeof CompanyRoute
  '/platform': typeof PlatformRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/developers/benchmarks': typeof DevelopersBenchmarksRoute
  '/developers/demos': typeof DevelopersDemosRoute
  '/developers/getting-started': typeof DevelopersGettingStartedRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/cookie-policy': typeof LegalCookiePolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/software-license': typeof LegalSoftwareLicenseRoute
  '/legal/support-policy': typeof LegalSupportPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/solutions/ai': typeof SolutionsAiRoute
  '/solutions/fabric': typeof SolutionsFabricRoute
  '/solutions/use-cases': typeof SolutionsUseCasesRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/company'
    | '/platform'
    | '/blog/$slug'
    | '/developers/benchmarks'
    | '/developers/demos'
    | '/developers/getting-started'
    | '/legal/acceptable-use'
    | '/legal/cookie-policy'
    | '/legal/privacy-policy'
    | '/legal/software-license'
    | '/legal/support-policy'
    | '/legal/terms-of-service'
    | '/solutions/ai'
    | '/solutions/fabric'
    | '/solutions/use-cases'
    | '/legal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/company'
    | '/platform'
    | '/blog/$slug'
    | '/developers/benchmarks'
    | '/developers/demos'
    | '/developers/getting-started'
    | '/legal/acceptable-use'
    | '/legal/cookie-policy'
    | '/legal/privacy-policy'
    | '/legal/software-license'
    | '/legal/support-policy'
    | '/legal/terms-of-service'
    | '/solutions/ai'
    | '/solutions/fabric'
    | '/solutions/use-cases'
    | '/legal'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/company'
    | '/platform'
    | '/blog/$slug'
    | '/developers/benchmarks'
    | '/developers/demos'
    | '/developers/getting-started'
    | '/legal/acceptable-use'
    | '/legal/cookie-policy'
    | '/legal/privacy-policy'
    | '/legal/software-license'
    | '/legal/support-policy'
    | '/legal/terms-of-service'
    | '/solutions/ai'
    | '/solutions/fabric'
    | '/solutions/use-cases'
    | '/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CompanyRoute: typeof CompanyRoute
  PlatformRoute: typeof PlatformRoute
  DevelopersBenchmarksRoute: typeof DevelopersBenchmarksRoute
  DevelopersDemosRoute: typeof DevelopersDemosRoute
  DevelopersGettingStartedRoute: typeof DevelopersGettingStartedRoute
  LegalAcceptableUseRoute: typeof LegalAcceptableUseRoute
  LegalCookiePolicyRoute: typeof LegalCookiePolicyRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalSoftwareLicenseRoute: typeof LegalSoftwareLicenseRoute
  LegalSupportPolicyRoute: typeof LegalSupportPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  SolutionsAiRoute: typeof SolutionsAiRoute
  SolutionsFabricRoute: typeof SolutionsFabricRoute
  SolutionsUseCasesRoute: typeof SolutionsUseCasesRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/use-cases': {
      id: '/solutions/use-cases'
      path: '/solutions/use-cases'
      fullPath: '/solutions/use-cases'
      preLoaderRoute: typeof SolutionsUseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/fabric': {
      id: '/solutions/fabric'
      path: '/solutions/fabric'
      fullPath: '/solutions/fabric'
      preLoaderRoute: typeof SolutionsFabricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/ai': {
      id: '/solutions/ai'
      path: '/solutions/ai'
      fullPath: '/solutions/ai'
      preLoaderRoute: typeof SolutionsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/support-policy': {
      id: '/legal/support-policy'
      path: '/legal/support-policy'
      fullPath: '/legal/support-policy'
      preLoaderRoute: typeof LegalSupportPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/software-license': {
      id: '/legal/software-license'
      path: '/legal/software-license'
      fullPath: '/legal/software-license'
      preLoaderRoute: typeof LegalSoftwareLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookie-policy': {
      id: '/legal/cookie-policy'
      path: '/legal/cookie-policy'
      fullPath: '/legal/cookie-policy'
      preLoaderRoute: typeof LegalCookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/acceptable-use': {
      id: '/legal/acceptable-use'
      path: '/legal/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof LegalAcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/getting-started': {
      id: '/developers/getting-started'
      path: '/developers/getting-started'
      fullPath: '/developers/getting-started'
      preLoaderRoute: typeof DevelopersGettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/demos': {
      id: '/developers/demos'
      path: '/developers/demos'
      fullPath: '/developers/demos'
      preLoaderRoute: typeof DevelopersDemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/benchmarks': {
      id: '/developers/benchmarks'
      path: '/developers/benchmarks'
      fullPath: '/developers/benchmarks'
      preLoaderRoute: typeof DevelopersBenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CompanyRoute: CompanyRoute,
  PlatformRoute: PlatformRoute,
  DevelopersBenchmarksRoute: DevelopersBenchmarksRoute,
  DevelopersDemosRoute: DevelopersDemosRoute,
  DevelopersGettingStartedRoute: DevelopersGettingStartedRoute,
  LegalAcceptableUseRoute: LegalAcceptableUseRoute,
  LegalCookiePolicyRoute: LegalCookiePolicyRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalSoftwareLicenseRoute: LegalSoftwareLicenseRoute,
  LegalSupportPolicyRoute: LegalSupportPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  SolutionsAiRoute: SolutionsAiRoute,
  SolutionsFabricRoute: SolutionsFabricRoute,
  SolutionsUseCasesRoute: SolutionsUseCasesRoute,
  LegalIndexRoute: LegalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
