/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as SolutionsMediaSecurityRouteImport } from './routes/solutions/media-security'
import { Route as SolutionsLlmOptimizationRouteImport } from './routes/solutions/llm-optimization'
import { Route as SolutionsAgenticHarnessRouteImport } from './routes/solutions/agentic-harness'
import { Route as PlatformPluginsRouteImport } from './routes/platform/plugins'
import { Route as PlatformInterfacesRouteImport } from './routes/platform/interfaces'
import { Route as PlatformFabricRouteImport } from './routes/platform/fabric'
import { Route as PlatformDatabasesRouteImport } from './routes/platform/databases'
import { Route as PlatformApplicationsRouteImport } from './routes/platform/applications'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal/terms-of-service'
import { Route as LegalSupportPolicyRouteImport } from './routes/legal/support-policy'
import { Route as LegalSoftwareLicenseRouteImport } from './routes/legal/software-license'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal/privacy-policy'
import { Route as LegalCookiePolicyRouteImport } from './routes/legal/cookie-policy'
import { Route as LegalAcceptableUseRouteImport } from './routes/legal/acceptable-use'
import { Route as DevelopersGettingStartedRouteImport } from './routes/developers/getting-started'
import { Route as DevelopersDemosRouteImport } from './routes/developers/demos'
import { Route as DevelopersBenchmarksRouteImport } from './routes/developers/benchmarks'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsMediaSecurityRoute = SolutionsMediaSecurityRouteImport.update({
  id: '/solutions/media-security',
  path: '/solutions/media-security',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsLlmOptimizationRoute =
  SolutionsLlmOptimizationRouteImport.update({
    id: '/solutions/llm-optimization',
    path: '/solutions/llm-optimization',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsAgenticHarnessRoute = SolutionsAgenticHarnessRouteImport.update({
  id: '/solutions/agentic-harness',
  path: '/solutions/agentic-harness',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformPluginsRoute = PlatformPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformInterfacesRoute = PlatformInterfacesRouteImport.update({
  id: '/interfaces',
  path: '/interfaces',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformFabricRoute = PlatformFabricRouteImport.update({
  id: '/fabric',
  path: '/fabric',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformDatabasesRoute = PlatformDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformApplicationsRoute = PlatformApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => PlatformRoute,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSupportPolicyRoute = LegalSupportPolicyRouteImport.update({
  id: '/legal/support-policy',
  path: '/legal/support-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSoftwareLicenseRoute = LegalSoftwareLicenseRouteImport.update({
  id: '/legal/software-license',
  path: '/legal/software-license',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiePolicyRoute = LegalCookiePolicyRouteImport.update({
  id: '/legal/cookie-policy',
  path: '/legal/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAcceptableUseRoute = LegalAcceptableUseRouteImport.update({
  id: '/legal/acceptable-use',
  path: '/legal/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersGettingStartedRoute =
  DevelopersGettingStartedRouteImport.update({
    id: '/developers/getting-started',
    path: '/developers/getting-started',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevelopersDemosRoute = DevelopersDemosRouteImport.update({
  id: '/developers/demos',
  path: '/developers/demos',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersBenchmarksRoute = DevelopersBenchmarksRouteImport.update({
  id: '/developers/benchmarks',
  path: '/developers/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/pricing': typeof PricingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/developers/benchmarks': typeof DevelopersBenchmarksRoute
  '/developers/demos': typeof DevelopersDemosRoute
  '/developers/getting-started': typeof DevelopersGettingStartedRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/cookie-policy': typeof LegalCookiePolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/software-license': typeof LegalSoftwareLicenseRoute
  '/legal/support-policy': typeof LegalSupportPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/platform/applications': typeof PlatformApplicationsRoute
  '/platform/databases': typeof PlatformDatabasesRoute
  '/platform/fabric': typeof PlatformFabricRoute
  '/platform/interfaces': typeof PlatformInterfacesRoute
  '/platform/plugins': typeof PlatformPluginsRoute
  '/solutions/agentic-harness': typeof SolutionsAgenticHarnessRoute
  '/solutions/llm-optimization': typeof SolutionsLlmOptimizationRoute
  '/solutions/media-security': typeof SolutionsMediaSecurityRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/pricing': typeof PricingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/developers/benchmarks': typeof DevelopersBenchmarksRoute
  '/developers/demos': typeof DevelopersDemosRoute
  '/developers/getting-started': typeof DevelopersGettingStartedRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/cookie-policy': typeof LegalCookiePolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/software-license': typeof LegalSoftwareLicenseRoute
  '/legal/support-policy': typeof LegalSupportPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/platform/applications': typeof PlatformApplicationsRoute
  '/platform/databases': typeof PlatformDatabasesRoute
  '/platform/fabric': typeof PlatformFabricRoute
  '/platform/interfaces': typeof PlatformInterfacesRoute
  '/platform/plugins': typeof PlatformPluginsRoute
  '/solutions/agentic-harness': typeof SolutionsAgenticHarnessRoute
  '/solutions/llm-optimization': typeof SolutionsLlmOptimizationRoute
  '/solutions/media-security': typeof SolutionsMediaSecurityRoute
  '/legal': typeof LegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/pricing': typeof PricingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/developers/benchmarks': typeof DevelopersBenchmarksRoute
  '/developers/demos': typeof DevelopersDemosRoute
  '/developers/getting-started': typeof DevelopersGettingStartedRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/cookie-policy': typeof LegalCookiePolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/software-license': typeof LegalSoftwareLicenseRoute
  '/legal/support-policy': typeof LegalSupportPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/platform/applications': typeof PlatformApplicationsRoute
  '/platform/databases': typeof PlatformDatabasesRoute
  '/platform/fabric': typeof PlatformFabricRoute
  '/platform/interfaces': typeof PlatformInterfacesRoute
  '/platform/plugins': typeof PlatformPluginsRoute
  '/solutions/agentic-harness': typeof SolutionsAgenticHarnessRoute
  '/solutions/llm-optimization': typeof SolutionsLlmOptimizationRoute
  '/solutions/media-security': typeof SolutionsMediaSecurityRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/platform'
    | '/pricing'
    | '/blog/$slug'
    | '/developers/benchmarks'
    | '/developers/demos'
    | '/developers/getting-started'
    | '/legal/acceptable-use'
    | '/legal/cookie-policy'
    | '/legal/privacy-policy'
    | '/legal/software-license'
    | '/legal/support-policy'
    | '/legal/terms-of-service'
    | '/platform/applications'
    | '/platform/databases'
    | '/platform/fabric'
    | '/platform/interfaces'
    | '/platform/plugins'
    | '/solutions/agentic-harness'
    | '/solutions/llm-optimization'
    | '/solutions/media-security'
    | '/legal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/platform'
    | '/pricing'
    | '/blog/$slug'
    | '/developers/benchmarks'
    | '/developers/demos'
    | '/developers/getting-started'
    | '/legal/acceptable-use'
    | '/legal/cookie-policy'
    | '/legal/privacy-policy'
    | '/legal/software-license'
    | '/legal/support-policy'
    | '/legal/terms-of-service'
    | '/platform/applications'
    | '/platform/databases'
    | '/platform/fabric'
    | '/platform/interfaces'
    | '/platform/plugins'
    | '/solutions/agentic-harness'
    | '/solutions/llm-optimization'
    | '/solutions/media-security'
    | '/legal'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/platform'
    | '/pricing'
    | '/blog/$slug'
    | '/developers/benchmarks'
    | '/developers/demos'
    | '/developers/getting-started'
    | '/legal/acceptable-use'
    | '/legal/cookie-policy'
    | '/legal/privacy-policy'
    | '/legal/software-license'
    | '/legal/support-policy'
    | '/legal/terms-of-service'
    | '/platform/applications'
    | '/platform/databases'
    | '/platform/fabric'
    | '/platform/interfaces'
    | '/platform/plugins'
    | '/solutions/agentic-harness'
    | '/solutions/llm-optimization'
    | '/solutions/media-security'
    | '/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
  PricingRoute: typeof PricingRoute
  DevelopersBenchmarksRoute: typeof DevelopersBenchmarksRoute
  DevelopersDemosRoute: typeof DevelopersDemosRoute
  DevelopersGettingStartedRoute: typeof DevelopersGettingStartedRoute
  LegalAcceptableUseRoute: typeof LegalAcceptableUseRoute
  LegalCookiePolicyRoute: typeof LegalCookiePolicyRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalSoftwareLicenseRoute: typeof LegalSoftwareLicenseRoute
  LegalSupportPolicyRoute: typeof LegalSupportPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  SolutionsAgenticHarnessRoute: typeof SolutionsAgenticHarnessRoute
  SolutionsLlmOptimizationRoute: typeof SolutionsLlmOptimizationRoute
  SolutionsMediaSecurityRoute: typeof SolutionsMediaSecurityRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/media-security': {
      id: '/solutions/media-security'
      path: '/solutions/media-security'
      fullPath: '/solutions/media-security'
      preLoaderRoute: typeof SolutionsMediaSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/llm-optimization': {
      id: '/solutions/llm-optimization'
      path: '/solutions/llm-optimization'
      fullPath: '/solutions/llm-optimization'
      preLoaderRoute: typeof SolutionsLlmOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/agentic-harness': {
      id: '/solutions/agentic-harness'
      path: '/solutions/agentic-harness'
      fullPath: '/solutions/agentic-harness'
      preLoaderRoute: typeof SolutionsAgenticHarnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/plugins': {
      id: '/platform/plugins'
      path: '/plugins'
      fullPath: '/platform/plugins'
      preLoaderRoute: typeof PlatformPluginsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/interfaces': {
      id: '/platform/interfaces'
      path: '/interfaces'
      fullPath: '/platform/interfaces'
      preLoaderRoute: typeof PlatformInterfacesRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/fabric': {
      id: '/platform/fabric'
      path: '/fabric'
      fullPath: '/platform/fabric'
      preLoaderRoute: typeof PlatformFabricRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/databases': {
      id: '/platform/databases'
      path: '/databases'
      fullPath: '/platform/databases'
      preLoaderRoute: typeof PlatformDatabasesRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/applications': {
      id: '/platform/applications'
      path: '/applications'
      fullPath: '/platform/applications'
      preLoaderRoute: typeof PlatformApplicationsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/support-policy': {
      id: '/legal/support-policy'
      path: '/legal/support-policy'
      fullPath: '/legal/support-policy'
      preLoaderRoute: typeof LegalSupportPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/software-license': {
      id: '/legal/software-license'
      path: '/legal/software-license'
      fullPath: '/legal/software-license'
      preLoaderRoute: typeof LegalSoftwareLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookie-policy': {
      id: '/legal/cookie-policy'
      path: '/legal/cookie-policy'
      fullPath: '/legal/cookie-policy'
      preLoaderRoute: typeof LegalCookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/acceptable-use': {
      id: '/legal/acceptable-use'
      path: '/legal/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof LegalAcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/getting-started': {
      id: '/developers/getting-started'
      path: '/developers/getting-started'
      fullPath: '/developers/getting-started'
      preLoaderRoute: typeof DevelopersGettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/demos': {
      id: '/developers/demos'
      path: '/developers/demos'
      fullPath: '/developers/demos'
      preLoaderRoute: typeof DevelopersDemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/benchmarks': {
      id: '/developers/benchmarks'
      path: '/developers/benchmarks'
      fullPath: '/developers/benchmarks'
      preLoaderRoute: typeof DevelopersBenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PlatformRouteChildren {
  PlatformApplicationsRoute: typeof PlatformApplicationsRoute
  PlatformDatabasesRoute: typeof PlatformDatabasesRoute
  PlatformFabricRoute: typeof PlatformFabricRoute
  PlatformInterfacesRoute: typeof PlatformInterfacesRoute
  PlatformPluginsRoute: typeof PlatformPluginsRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformApplicationsRoute: PlatformApplicationsRoute,
  PlatformDatabasesRoute: PlatformDatabasesRoute,
  PlatformFabricRoute: PlatformFabricRoute,
  PlatformInterfacesRoute: PlatformInterfacesRoute,
  PlatformPluginsRoute: PlatformPluginsRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
  PricingRoute: PricingRoute,
  DevelopersBenchmarksRoute: DevelopersBenchmarksRoute,
  DevelopersDemosRoute: DevelopersDemosRoute,
  DevelopersGettingStartedRoute: DevelopersGettingStartedRoute,
  LegalAcceptableUseRoute: LegalAcceptableUseRoute,
  LegalCookiePolicyRoute: LegalCookiePolicyRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalSoftwareLicenseRoute: LegalSoftwareLicenseRoute,
  LegalSupportPolicyRoute: LegalSupportPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  SolutionsAgenticHarnessRoute: SolutionsAgenticHarnessRoute,
  SolutionsLlmOptimizationRoute: SolutionsLlmOptimizationRoute,
  SolutionsMediaSecurityRoute: SolutionsMediaSecurityRoute,
  LegalIndexRoute: LegalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
