//! www — Phase 48 static-crate entry point.
//!
//! Generated by scripts/migrate_app_to_static.py. The `#[path]` mod
//! declarations let the cargo build reach the existing modules/ and
//! resources/ files without moving them — both the dylib path
//! (yeti-compiler flat-src copy) and the static path (this crate)
//! share source during the migration window. Slice 5 retires the
//! dylib path; a follow-up commit then moves modules/ → src/ and
//! drops the `#[path]` attrs.


use yeti_sdk::extensions::{RegistrationContext, Service};
use yeti_sdk::prelude::*;

// ── Resources ───────────────────────────────────────────────────────
#[path = "../resources/blog_image.rs"]
mod blog_image;
#[path = "../resources/blog_sync.rs"]
mod blog_sync;

/// Factory invoked by the customer deployment binary.
pub fn service() -> Box<dyn Service> {
    Box::new(WwwService)
}

struct WwwService;

impl Service for WwwService {
    fn id(&self) -> &'static str {
        "www"
    }

    fn name(&self) -> &'static str {
        "Website"
    }

    fn is_extension(&self) -> bool {
        false
    }

    fn config_yaml(&self) -> Option<&'static str> {
        Some(include_str!("../config.yaml"))
    }

    fn schemas(&self) -> Vec<&'static str> {
        vec![include_str!("../schemas/schema.graphql")]
    }

    fn resources(&self, ctx: &mut RegistrationContext) -> yeti_sdk::error::Result<()> {
        ctx.add_resource(Box::new(blog_image::BlogImage));
        ctx.add_resource(Box::new(blog_sync::BlogSync));
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn factory_returns_configured_service() {
        let svc = service();
        assert_eq!(svc.id(), "www");
    }

    #[test]
    fn factory_satisfies_server_builder_bounds() {
        fn assert_factory_bounds<F>(_: F)
        where
            F: Fn() -> Box<dyn Service> + Send + Sync + 'static,
        {
        }
        assert_factory_bounds(service);
    }
}
